/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Frm;

import BO.ProductoBO;
import Clases.Producto;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import javax.swing.JDialog;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableCellRenderer;

/**
 *
 * @author ncmen
 */
public class Frm_Pruebas extends javax.swing.JFrame {

    
    public void mostrarProductos(){
    pbo.listarProductos(tabla);
    }
    
    public void mostrarFiltrado(int d){
        pbo.listarFiltrado(tabla, d);
    }
    /**
     * Creates new form FramePruebas
     */
    public Frm_Pruebas() {
        initComponents();
        this.setLocationRelativeTo(null);
        mostrarProductos();

        
        p_Agregar.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                JDialog dialog = new Form_Agregar(Frm_Pruebas.this, true);
                dialog.addWindowListener(new WindowAdapter() {
                    @Override
                    public void windowClosed(WindowEvent e){
                        mostrarProductos();
                    }
                });
                dialog.setVisible(true);
            }           
        });
        
    }
    private ProductoBO pbo = new ProductoBO();
    
    
 

    
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jToggleButton1 = new javax.swing.JToggleButton();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabla = new javax.swing.JTable();
        BG = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        p_Agregar = new javax.swing.JMenuItem();
        p_Eliminar = new javax.swing.JMenuItem();
        p_Editar = new javax.swing.JMenuItem();
        p_Buscar = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        pl_Agregar = new javax.swing.JMenuItem();
        pl_Eliminar = new javax.swing.JMenuItem();
        pl_Editar = new javax.swing.JMenuItem();
        pl_Buscar = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(1000, 500));
        setMinimumSize(new java.awt.Dimension(1000, 500));
        setPreferredSize(new java.awt.Dimension(1000, 500));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jToggleButton1.setText("SOLO DESCUENTO / SIN DESCUENTO");
        jToggleButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jToggleButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 10, 270, 20));

        jButton1.setText("MUESTRA TODO");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(345, 10, 130, -1));

        jButton2.setText("jButton2");
        jPanel1.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 390, -1, -1));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jScrollPane2.setViewportView(jTable1);

        jPanel1.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 40, 440, 330));

        tabla.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        tabla.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        tabla.setFocusable(false);
        jScrollPane1.setViewportView(tabla);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 40, -1, 330));

        BG.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imágenes/soy admin.jpg"))); // NOI18N
        jPanel1.add(BG, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1000, 470));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1000, -1));

        jMenu1.setText("Productos");

        p_Agregar.setText("Agregar");
        p_Agregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                p_AgregarActionPerformed(evt);
            }
        });
        jMenu1.add(p_Agregar);

        p_Eliminar.setText("Eliminar");
        p_Eliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                p_EliminarActionPerformed(evt);
            }
        });
        jMenu1.add(p_Eliminar);

        p_Editar.setText("Editar");
        jMenu1.add(p_Editar);

        p_Buscar.setText("Buscar");
        jMenu1.add(p_Buscar);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Planes");

        pl_Agregar.setText("Agregar");
        jMenu2.add(pl_Agregar);

        pl_Eliminar.setText("Eliminar");
        pl_Eliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pl_EliminarActionPerformed(evt);
            }
        });
        jMenu2.add(pl_Eliminar);

        pl_Editar.setText("Editar");
        jMenu2.add(pl_Editar);

        pl_Buscar.setText("Buscar");
        jMenu2.add(pl_Buscar);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void p_EliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_p_EliminarActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_p_EliminarActionPerformed

    private void pl_EliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pl_EliminarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pl_EliminarActionPerformed

    private void jToggleButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton1ActionPerformed
        // TODO add your handling code here:
        if(jToggleButton1.isSelected()){
            //Filtrar
            jToggleButton1.setText("TIENE DESCUENTO");
            mostrarFiltrado(1);
            
        }
        else{
            //No Filtra
            jToggleButton1.setText("NO TIENE DESCUENTO");
            mostrarFiltrado(0);
        }
    }//GEN-LAST:event_jToggleButton1ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        jToggleButton1.setText("SOLO DESCUENTO / SIN DESCUENTO");
        mostrarProductos();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void p_AgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_p_AgregarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_p_AgregarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Frm_Pruebas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Frm_Pruebas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Frm_Pruebas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Frm_Pruebas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Frm_Pruebas().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel BG;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JToggleButton jToggleButton1;
    private javax.swing.JMenuItem p_Agregar;
    private javax.swing.JMenuItem p_Buscar;
    private javax.swing.JMenuItem p_Editar;
    private javax.swing.JMenuItem p_Eliminar;
    private javax.swing.JMenuItem pl_Agregar;
    private javax.swing.JMenuItem pl_Buscar;
    private javax.swing.JMenuItem pl_Editar;
    private javax.swing.JMenuItem pl_Eliminar;
    private javax.swing.JTable tabla;
    // End of variables declaration//GEN-END:variables
}
