/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Frm;

import java.awt.Image;
import javax.swing.ImageIcon;
import javax.swing.Icon;
import javax.swing.JLabel;
import Clases.Tiempopro;
import javax.swing.JTextArea;
/**
 *
 * @author Moises
 */
public class Frm_Menu extends javax.swing.JFrame {

    Tiempopro time = new Tiempopro();
    /**
     * Creates new form NewJFrame
     */
    public Frm_Menu() {
        
        initComponents();
        mostrarTiempo();
        bloquearTexto(jTextArea1);

    }
    
    public void mostrarTiempo(){
    
    FECHA.setText(time.fechacomp);
    HORA.setText(time.horacomp);
}
    public void bloquearTexto(JTextArea t){
        t.setEnabled(false);
        t.setHighlighter(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btn_Salir = new javax.swing.JButton();
        btn_ClientesNuevos = new javax.swing.JButton();
        btn_ClientesPlan = new javax.swing.JButton();
        btn_Admin = new javax.swing.JButton();
        img_skltn = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jLabel1 = new javax.swing.JLabel();
        FECHA = new javax.swing.JLabel();
        HORA = new javax.swing.JLabel();
        img_bg = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Menú Principal");
        setMaximumSize(new java.awt.Dimension(1000, 520));
        setMinimumSize(new java.awt.Dimension(1000, 520));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(102, 102, 102,200));
        jPanel1.setForeground(new java.awt.Color(102, 102, 102,200));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btn_Salir.setBackground(new java.awt.Color(255, 51, 51));
        btn_Salir.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btn_Salir.setText("SALIR");
        btn_Salir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_SalirActionPerformed(evt);
            }
        });
        jPanel1.add(btn_Salir, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 420, -1, 20));

        btn_ClientesNuevos.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btn_ClientesNuevos.setText("CLIENTES NUEVOS");
        btn_ClientesNuevos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_ClientesNuevosActionPerformed(evt);
            }
        });
        jPanel1.add(btn_ClientesNuevos, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 110, 170, 40));

        btn_ClientesPlan.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btn_ClientesPlan.setText("CLIENTES y PLANES");
        btn_ClientesPlan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_ClientesPlanActionPerformed(evt);
            }
        });
        jPanel1.add(btn_ClientesPlan, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 170, 170, 40));

        btn_Admin.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btn_Admin.setText("ADMINISTRACIÓN");
        btn_Admin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_AdminActionPerformed(evt);
            }
        });
        jPanel1.add(btn_Admin, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 230, 170, 40));

        img_skltn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imágenes/skeleton.jpg"))); // NOI18N
        img_skltn.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.add(img_skltn, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 110, 210, 280));

        jTextArea1.setColumns(20);
        jTextArea1.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        jTextArea1.setRows(5);
        jTextArea1.setText("Para agregar nuevos clientes \t\t> CLIENTES NUEVOS\nPara modificar clientes existentes\t> CLIENTES Y PLANES\nPara modificar planes, productos, etc...\t> ADMINISTRACIÓN\n\n\n\n\nAtte. Master");
        jScrollPane1.setViewportView(jTextArea1);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 110, 490, 190));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setText("MENÚ PRINCIPAL");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 30, 160, 30));

        FECHA.setBackground(new java.awt.Color(255, 255, 102));
        FECHA.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        FECHA.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.add(FECHA, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 420, 70, 20));

        HORA.setBackground(new java.awt.Color(255, 255, 102));
        HORA.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        HORA.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.add(HORA, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 420, 70, 20));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 980, 460));

        img_bg.setForeground(new java.awt.Color(153, 153, 153,255));
        img_bg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imágenes/bg_menu.jpg"))); // NOI18N
        img_bg.setToolTipText("");
        getContentPane().add(img_bg, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        setSize(new java.awt.Dimension(1016, 507));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btn_SalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_SalirActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_btn_SalirActionPerformed

    private void btn_ClientesNuevosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_ClientesNuevosActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        Frm_ClienteNuevo ventana = new Frm_ClienteNuevo();
        ventana.setVisible(true);
    }//GEN-LAST:event_btn_ClientesNuevosActionPerformed

    private void btn_ClientesPlanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_ClientesPlanActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_ClientesPlanActionPerformed

    private void btn_AdminActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_AdminActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_AdminActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Frm_Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Frm_Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Frm_Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Frm_Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Frm_Menu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel FECHA;
    private javax.swing.JLabel HORA;
    private javax.swing.JButton btn_Admin;
    private javax.swing.JButton btn_ClientesNuevos;
    private javax.swing.JButton btn_ClientesPlan;
    private javax.swing.JButton btn_Salir;
    private javax.swing.JLabel img_bg;
    private javax.swing.JLabel img_skltn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    // End of variables declaration//GEN-END:variables
}
