/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Frm;

import BO.ProductoBO;
import Clases.Producto;
import Clases.Conexion;
import java.awt.Color;
import java.awt.Container;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JComboBox;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author ncmen
 */
public class Frm_Administracion extends javax.swing.JFrame {

    
    
       private ProductoBO pbo = new ProductoBO();
    /**
     * Creates new form Frm_Administracion
     */
    public Frm_Administracion() {
        initComponents();
        mostrarProductos();
        Btn_Descuento.setSelected(false);
        txt_Valor_Descuento.setEnabled(false);
        txt_ID_Prod.setEditable(false);
        
    }

      public void mostrarProductos(){
        pbo.listarProductos(tablaProductos);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        txt_ID_Prod = new javax.swing.JTextField();
        txt_Nombre_Prod = new javax.swing.JTextField();
        txt_Precio_Prod = new javax.swing.JTextField();
        txt_Valor_Descuento = new javax.swing.JTextField();
        txt_ID_Prod1 = new javax.swing.JTextField();
        txt_Nombre_Prod1 = new javax.swing.JTextField();
        txt_Precio_Prod1 = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        btn_Limpiar = new javax.swing.JButton();
        btn_Agregar = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        btn_Eliminar = new javax.swing.JButton();
        jLabel14 = new javax.swing.JLabel();
        btn_Editar = new javax.swing.JButton();
        jLabel15 = new javax.swing.JLabel();
        btn_Buscar = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        Btn_Descuento = new javax.swing.JToggleButton();
        btn_getID = new javax.swing.JButton();
        btn_Volver = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaProductos = new javax.swing.JTable();
        jLabel7 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Menu Administrativo");
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setMaximumSize(new java.awt.Dimension(1000, 500));
        setMinimumSize(new java.awt.Dimension(1000, 500));
        setPreferredSize(new java.awt.Dimension(1000, 500));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setMaximumSize(new java.awt.Dimension(1000, 500));
        jPanel1.setMinimumSize(new java.awt.Dimension(1000, 500));
        jPanel1.setPreferredSize(new java.awt.Dimension(1000, 500));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("ID PRODUCTO");
        jLabel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jLabel3.setOpaque(true);
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 142, -1));

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("NOMBRE PRODUCTO");
        jLabel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jLabel2.setOpaque(true);
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, 142, -1));

        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("PRECIO PRODUCTO");
        jLabel5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jLabel5.setOpaque(true);
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 100, 142, -1));

        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("TIENE DESCUENTO");
        jLabel4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jLabel4.setOpaque(true);
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(22, 140, 140, -1));

        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel10.setText("VALOR DESCUENTO");
        jLabel10.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jLabel10.setOpaque(true);
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 180, 142, 20));

        txt_ID_Prod.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_ID_ProdActionPerformed(evt);
            }
        });
        jPanel1.add(txt_ID_Prod, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 20, 142, -1));
        jPanel1.add(txt_Nombre_Prod, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 60, 142, -1));
        jPanel1.add(txt_Precio_Prod, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 100, 142, -1));

        txt_Valor_Descuento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_Valor_DescuentoActionPerformed(evt);
            }
        });
        jPanel1.add(txt_Valor_Descuento, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 180, 142, -1));

        txt_ID_Prod1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_ID_Prod1ActionPerformed(evt);
            }
        });
        jPanel1.add(txt_ID_Prod1, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 250, 142, -1));
        jPanel1.add(txt_Nombre_Prod1, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 290, 142, -1));
        jPanel1.add(txt_Precio_Prod1, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 330, 142, -1));

        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("ID PLAN");
        jLabel6.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jLabel6.setOpaque(true);
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 250, 142, -1));

        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("NOMBRE PLAN");
        jLabel8.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jLabel8.setOpaque(true);
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 290, 142, -1));

        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel12.setText("PRECIO PLAN");
        jLabel12.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jLabel12.setOpaque(true);
        jPanel1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 330, 142, -1));

        btn_Limpiar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imágenes/icon_limpiar2.png"))); // NOI18N
        btn_Limpiar.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        btn_Limpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_LimpiarActionPerformed(evt);
            }
        });
        jPanel1.add(btn_Limpiar, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 370, -1, -1));

        btn_Agregar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imágenes/icon_agregar.png"))); // NOI18N
        btn_Agregar.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        btn_Agregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_AgregarActionPerformed(evt);
            }
        });
        jPanel1.add(btn_Agregar, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 370, -1, -1));

        jLabel11.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel11.setText("LIMPIAR");
        jLabel11.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jLabel11.setOpaque(true);
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 440, 50, 20));

        jLabel13.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        jLabel13.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel13.setText("AÑADIR");
        jLabel13.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jLabel13.setOpaque(true);
        jPanel1.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 440, 50, 20));

        btn_Eliminar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imágenes/icon_eliminar.png"))); // NOI18N
        btn_Eliminar.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        btn_Eliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_EliminarActionPerformed(evt);
            }
        });
        jPanel1.add(btn_Eliminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 370, 60, -1));

        jLabel14.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        jLabel14.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel14.setText("ELIMINAR");
        jLabel14.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jLabel14.setOpaque(true);
        jPanel1.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 440, 50, 20));

        btn_Editar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imágenes/icon_edit.png"))); // NOI18N
        btn_Editar.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        btn_Editar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_EditarActionPerformed(evt);
            }
        });
        jPanel1.add(btn_Editar, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 370, 60, -1));

        jLabel15.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        jLabel15.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel15.setText("EDITAR");
        jLabel15.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jLabel15.setOpaque(true);
        jPanel1.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 440, 50, 20));

        btn_Buscar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imágenes/icon_buscar.png"))); // NOI18N
        btn_Buscar.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        btn_Buscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_BuscarActionPerformed(evt);
            }
        });
        jPanel1.add(btn_Buscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 370, -1, -1));

        jLabel9.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setText("BUSCAR");
        jLabel9.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jLabel9.setOpaque(true);
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 440, 50, 20));

        Btn_Descuento.setText("Descuento");
        Btn_Descuento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_DescuentoActionPerformed(evt);
            }
        });
        jPanel1.add(Btn_Descuento, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 140, -1, -1));

        btn_getID.setText("jButton1");
        btn_getID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_getIDActionPerformed(evt);
            }
        });
        jPanel1.add(btn_getID, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 360, -1, -1));

        btn_Volver.setBackground(new java.awt.Color(255, 51, 51));
        btn_Volver.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btn_Volver.setText("VOLVER");
        btn_Volver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_VolverActionPerformed(evt);
            }
        });
        jPanel1.add(btn_Volver, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 430, -1, 20));

        tablaProductos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tablaProductos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tablaProductosMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tablaProductos);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(422, 26, 530, 300));

        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imágenes/soy admin.jpg"))); // NOI18N
        jLabel7.setText(" ");
        jLabel7.setMaximumSize(new java.awt.Dimension(1000, 500));
        jLabel7.setMinimumSize(new java.awt.Dimension(1000, 500));
        jLabel7.setPreferredSize(new java.awt.Dimension(1000, 500));
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(-450, -20, 1750, 520));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        getAccessibleContext().setAccessibleDescription("");

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void txt_ID_ProdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_ID_ProdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_ID_ProdActionPerformed

    private void txt_ID_Prod1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_ID_Prod1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_ID_Prod1ActionPerformed

    private void tablaProductosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tablaProductosMouseClicked
        // TODO add your handling code here:
        int seleccion = tablaProductos.rowAtPoint(evt.getPoint());
        txt_ID_Prod.setText(tablaProductos.getValueAt(seleccion, 0)+"");
        txt_ID_Prod.setEditable(false);
        txt_Nombre_Prod.setText(tablaProductos.getValueAt(seleccion, 1)+"");
        txt_Precio_Prod.setText(tablaProductos.getValueAt(seleccion, 2)+"");
       // txt_Descuento_Prod.setText(tablaProductos.getValueAt(seleccion, 3)+"");
        txt_Valor_Descuento.setText(tablaProductos.getValueAt(seleccion, 4)+"");

    }//GEN-LAST:event_tablaProductosMouseClicked

    private void btn_LimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_LimpiarActionPerformed
        // TODO add your handling code here:
        limpiar();
        mostrarProductos();
    }//GEN-LAST:event_btn_LimpiarActionPerformed
 public void Agregar(){
        String mensaje = "";
        Producto p = new Producto();
                p.setID_prod(txt_ID_Prod.getText());
                p.setNombre_prod(txt_Nombre_Prod.getText());
                p.setPrecio_prod(Integer.parseInt(txt_Precio_Prod.getText()));
               // p.setDescuento_prod(Integer.parseInt(txt_Descuento_Prod.getText()));
                p.setValor_descuento_prod(Integer.parseInt(txt_Valor_Descuento.getText()));

                mensaje = pbo.agregarProducto(p);

                JOptionPane.showMessageDialog(null, mensaje);
                limpiar();
                mostrarProductos();
 }
     public void limpiar(){
        String vacio = "";
        txt_ID_Prod.setText(vacio);
        txt_Nombre_Prod.setText(vacio);
        txt_Precio_Prod.setText(vacio);
        //txt_Descuento_Prod.setText(vacio);
        txt_Valor_Descuento.setText(vacio);
    }
    
    
    private void btn_AgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_AgregarActionPerformed
        // TODO add your handling code here:

        if (txt_ID_Prod.getText().isEmpty() || txt_Nombre_Prod.getText().isEmpty()
            || txt_Precio_Prod.getText().isEmpty() || /*txt_Descuento_Prod.getText().isEmpty() ||*/ txt_Valor_Descuento.getText().isEmpty()){
            JOptionPane.showMessageDialog(null, "Llene todos los campos", "Para agregar un Producto", JOptionPane.WARNING_MESSAGE);
      
        }
        Agregar();
    }//GEN-LAST:event_btn_AgregarActionPerformed

    private void btn_EliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_EliminarActionPerformed
        // TODO add your handling code here:
        if (txt_ID_Prod.getText().isEmpty()){
            JOptionPane.showMessageDialog(null, "No puede faltar el ID del producto.", "Para eliminar un Producto", JOptionPane.WARNING_MESSAGE);
        }
        else if( JOptionPane.showConfirmDialog(rootPane, "Se eliminará el producto, ¿Desea Continuar?",
            "Eliminar Producto", JOptionPane.WARNING_MESSAGE, JOptionPane.YES_NO_OPTION) == JOptionPane.YES_OPTION){
        eliminarProducto();
        }
    }//GEN-LAST:event_btn_EliminarActionPerformed
    public void eliminarProducto(){
        String mensaje = pbo.eliminarProducto(Integer.parseInt(txt_ID_Prod.getText()));
        JOptionPane.showMessageDialog(null, mensaje);
        limpiar();
        mostrarProductos();
        
    }
    private void btn_EditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_EditarActionPerformed
        // TODO add your handling code here:
        if (txt_ID_Prod.getText().isEmpty() || txt_Nombre_Prod.getText().isEmpty()
            || txt_Precio_Prod.getText().isEmpty() || /*txt_Descuento_Prod.getText().isEmpty() ||*/ txt_Valor_Descuento.getText().isEmpty()){
            JOptionPane.showMessageDialog(null, "Llene todos los campos", "Para editar un Producto", JOptionPane.WARNING_MESSAGE);
        } else {
            Producto p = new Producto();

            p.setID_prod(txt_ID_Prod.getText());
            p.setNombre_prod(txt_Nombre_Prod.getText());
            p.setPrecio_prod(Integer.parseInt(txt_Precio_Prod.getText()));
           // p.setDescuento_prod(Integer.parseInt(txt_Descuento_Prod.getText()));
            p.setValor_descuento_prod(Integer.parseInt(txt_Valor_Descuento.getText()));
           

            if( JOptionPane.showConfirmDialog(rootPane, "Se actualizará el producto, ¿Desea Continuar?",
                "Actualizar Registro", JOptionPane.WARNING_MESSAGE, JOptionPane.YES_NO_OPTION) == JOptionPane.YES_OPTION){
            String mensaje = pbo.modificarProducto(p);
            JOptionPane.showMessageDialog(null, mensaje);
            limpiar();
            mostrarProductos();
        }
        }
    }//GEN-LAST:event_btn_EditarActionPerformed

    private void btn_BuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_BuscarActionPerformed
        // TODO add your handling code here:
        if (txt_ID_Prod.getText().isEmpty()){
            JOptionPane.showMessageDialog(null, "Es necesario el ID del producto", "Para buscar un Producto", JOptionPane.WARNING_MESSAGE);
        } else {
            int ID = Integer.parseInt(txt_ID_Prod.getText());
            pbo.BuscarProducto(ID, tablaProductos);

        }
    }//GEN-LAST:event_btn_BuscarActionPerformed

    private void btn_VolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_VolverActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        Frm_Menu ventana = new Frm_Menu();
        ventana.setVisible(true);
    }//GEN-LAST:event_btn_VolverActionPerformed

    private void txt_Valor_DescuentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_Valor_DescuentoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_Valor_DescuentoActionPerformed

    private void Btn_DescuentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_DescuentoActionPerformed
        // TODO add your handling code here:
     
        
            if(Btn_Descuento.isSelected()){
              txt_Valor_Descuento.setEnabled(true);
              txt_Valor_Descuento.setEditable(true);
            }
            else{
            
                txt_Valor_Descuento.setEnabled(false);
                txt_Valor_Descuento.setText("");
            }
        
    }//GEN-LAST:event_Btn_DescuentoActionPerformed

    private void btn_getIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_getIDActionPerformed
        // TODO add your handling code here:
       // if (txt_Nombre_Prod.getText().isEmpty()|| txt_Precio_Prod.getText().isEmpty() || txt_Valor_Descuento.getText().isEmpty()) 
           
      
       
        
    }//GEN-LAST:event_btn_getIDActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Frm_Administracion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Frm_Administracion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Frm_Administracion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Frm_Administracion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Frm_Administracion().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToggleButton Btn_Descuento;
    private javax.swing.JButton btn_Agregar;
    private javax.swing.JButton btn_Buscar;
    private javax.swing.JButton btn_Editar;
    private javax.swing.JButton btn_Eliminar;
    private javax.swing.JButton btn_Limpiar;
    private javax.swing.JButton btn_Volver;
    private javax.swing.JButton btn_getID;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tablaProductos;
    private javax.swing.JTextField txt_ID_Prod;
    private javax.swing.JTextField txt_ID_Prod1;
    private javax.swing.JTextField txt_Nombre_Prod;
    private javax.swing.JTextField txt_Nombre_Prod1;
    private javax.swing.JTextField txt_Precio_Prod;
    private javax.swing.JTextField txt_Precio_Prod1;
    private javax.swing.JTextField txt_Valor_Descuento;
    // End of variables declaration//GEN-END:variables

   
}
